---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/5D9037A9106244F3/Heimdall/data:/config
    ports:
      - 80:80
    restart: unless-stopped
