version: '3.3'
services:
    deemix:
        image: registry.gitlab.com/bockiii/deemix-docker
        container_name: Deemix
        volumes:
            - /mnt/5D9037A9106244F3/Music/Deemix:/downloads
            - /your/config/location:/config
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK_SET=022
        ports:
            - 6595:6595
